// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb5f5s5sQMdTwc1pZoBsjNQIU6rDCulhw',
    appId: '1:122867724764:web:bf1d6882f53171cae09f19',
    messagingSenderId: '122867724764',
    projectId: 'tailor-app-83b4c',
    authDomain: 'tailor-app-83b4c.firebaseapp.com',
    storageBucket: 'tailor-app-83b4c.appspot.com',
    measurementId: 'G-B3V19MYXRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAutFGZ8XzGCFeAeN7t6RjVR3K3BEc8bHM',
    appId: '1:122867724764:android:09f771988dcf6a02e09f19',
    messagingSenderId: '122867724764',
    projectId: 'tailor-app-83b4c',
    storageBucket: 'tailor-app-83b4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCilOnqwu8cMToGPg8rxpbhB-dJ-IKOiU4',
    appId: '1:122867724764:ios:29b12a7a8d7e9d51e09f19',
    messagingSenderId: '122867724764',
    projectId: 'tailor-app-83b4c',
    storageBucket: 'tailor-app-83b4c.appspot.com',
    iosClientId: '122867724764-ksdtenvp0oa1q22hqohul2bnasqv19e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ect',
  );
}
